M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Fri 17 Jan 2025 06:31:41 AM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-17T06:31:41-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X5.5445Y-4.2612
X5.5445Y-4.4522
T2
X5.6638Y-4.2494
X5.6638Y-4.464
T3
X2.126Y-2.126
X2.126Y-5.7087
X5.748Y-2.126
X5.748Y-5.748
M30
